{{- if index .Values "minio-infra" "enabled" }}
{{- if index .Values "minio-infra" "minio" "storage" "local" "enabled" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "data-stack.fullname" . }}-minio-storage-init
  namespace: {{ index .Values "minio-infra" "global" "namespace" }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "data-stack.fullname" . }}-minio-storage-init
    spec:
      restartPolicy: OnFailure
      hostNetwork: true
      hostPID: true
      containers:
      - name: minio-storage-init
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - |
          nsenter -t 1 -m -u -n -i -- sh -c "
            mkdir -p {{ index .Values "minio-infra" "minio" "storage" "local" "path" }}
            chmod 777 {{ index .Values "minio-infra" "minio" "storage" "local" "path" }}
            echo 'MinIO storage directory created'
          "
        securityContext:
          privileged: true
      tolerations:
      - operator: Exists
{{- end }}
{{- end }}
