{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.tenant.name }}-ingress
  namespace: {{ .Values.tenant.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: {{ index .Values.ingress.api.annotations "nginx.ingress.kubernetes.io/proxy-body-size" | quote }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
spec:
  ingressClassName: nginx
  rules:
  # Console Ingress
  - host: {{ .Values.ingress.console.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.tenant.name }}-console
            port:
              number: 9090
  # API Ingress
  - host: {{ .Values.ingress.api.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 80
{{- end }}
