{{- if .Values.tenant.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration
  namespace: {{ include "minio.namespace" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="{{ .Values.minio.rootUser }}"
    export MINIO_ROOT_PASSWORD="{{ .Values.minio.rootPassword }}"
    export MINIO_BROWSER="{{ .Values.minio.browser }}"
{{- end }}
